// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc172.NorthernForce;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Ultrasonic;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveBaseCANTalon1;
    public static CANTalon driveBaseCANTalon2;
    public static CANTalon driveBaseCANTalon3;
    public static CANTalon driveBaseCANTalon4;
    public static Ultrasonic ultrasonicSensor;
    public static RobotDrive driveBaseRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveBaseCANTalon1 = new CANTalon(0);
        LiveWindow.addActuator("DriveBase", "CAN Talon 1", driveBaseCANTalon1);
        driveBaseCANTalon2 = new CANTalon(1);
        LiveWindow.addActuator("DriveBase", "CAN Talon 2", driveBaseCANTalon2);
        driveBaseCANTalon3 = new CANTalon(2);
        LiveWindow.addActuator("DriveBase", "CAN Talon 3", driveBaseCANTalon3);
        driveBaseCANTalon4 = new CANTalon(3);
        ultrasonicSensor = new Ultrasonic(1,1);
        LiveWindow.addActuator("DriveBase", "CAN Talon 4", driveBaseCANTalon4);
        driveBaseRobotDrive = new RobotDrive(driveBaseCANTalon1, driveBaseCANTalon2, driveBaseCANTalon3, driveBaseCANTalon4);
        driveBaseRobotDrive.setSafetyEnabled(true);
        driveBaseRobotDrive.setExpiration(0.1);
        driveBaseRobotDrive.setSensitivity(0.5);
        driveBaseRobotDrive.setMaxOutput(1.0);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
